# -*- coding: utf-8 -*-
"""
report/formatter.py
===================
ASCII layout helpers for the final report document.

  format_cover_page() — generates the title + table-of-contents block.
  format_section()    — wraps a single section in its header/footer frame.
"""

import re
import textwrap
from datetime import date

from config import WIDTH


def format_cover_page(topic: str) -> str:
    """
    Build an ASCII cover page with a centred title and table of contents.

    Args:
        topic: Research topic string (will be uppercased and centred).

    Returns:
        Formatted cover-page string.
    """
    thick_line = "═" * WIDTH
    thin_line  = "─" * WIDTH
    today      = date.today().strftime("%B %d, %Y")

    title_wrapped = textwrap.fill(
        topic.upper(), width=WIDTH, break_long_words=False
    )
    title_centred = "\n".join(
        line.center(WIDTH) for line in title_wrapped.splitlines()
    )

    return (
        f"\n{thick_line}\n"
        f"\n"
        f"{'RESEARCH REPORT'.center(WIDTH)}\n"
        f"\n"
        f"{thin_line}\n"
        f"\n"
        f"{title_centred}\n"
        f"\n"
        f"{thin_line}\n"
        f"\n"
        f"{'Date: ' + today:>{WIDTH}}\n"
        f"{'Generated by: AI Research Agent':>{WIDTH}}\n"
        f"\n"
        f"{thick_line}\n"
        f"\n"
        f"{'TABLE OF CONTENTS'.center(WIDTH)}\n"
        f"{thin_line}\n"
        f"  1.  Introduction\n"
        f"  2.  Key Findings\n"
        f"  3.  Challenges\n"
        f"  4.  Future Scope\n"
        f"  5.  Conclusion\n"
        f"{thick_line}\n"
    )


def format_section(number: int, title: str, content: str) -> str:
    """
    Wrap section content in a numbered ASCII frame with proper indentation.

    Bullet lines receive a hanging indent for readability. Per-section line
    caps prevent runaway model output from inflating the report.

    Args:
        number:  1-indexed section number.
        title:   Section display title (e.g. "KEY FINDINGS").
        content: Raw content string from the LLM (or fallback).

    Returns:
        Formatted section string ready to append to the report.
    """
    thin_line  = "─" * WIDTH
    thick_line = "═" * WIDTH

    # Normalise inline bullets: "text • next" → newline before each •
    content = re.sub(r'\s*•\s*', '\n• ', content)
    # Normalise dash-based bullets that start with a capital letter
    content = re.sub(r'\s*-\s{1,3}(?=[A-Z])', '\n• ', content)

    lines           = content.split('\n')
    formatted_lines = []

    for line in lines:
        line = line.strip()
        if not line:
            continue

        if line.startswith('•'):
            wrapped = textwrap.fill(
                line,
                width             = WIDTH,
                initial_indent    = '  ',
                subsequent_indent = '      ',   # hanging indent
                break_long_words  = False,
            )
        else:
            wrapped = textwrap.fill(
                line,
                width            = WIDTH,
                break_long_words = False,
            )

        if wrapped:
            formatted_lines.append(wrapped)

    # Per-section line caps — generous enough for quality content
    MAX_LINES = {1: 20, 2: 25, 3: 20, 4: 20, 5: 20}
    limit = MAX_LINES.get(number, 12)

    if len(formatted_lines) > limit:
        formatted_lines = formatted_lines[:limit]
        formatted_lines.append("  [output truncated]")

    body = "\n".join(formatted_lines)

    return (
        f"\n{thick_line}\n"
        f"  {number}. {title}\n"
        f"{thin_line}\n"
        f"{body}\n"
    )
